config/routes.rb
Rails.application.routes.draw do
  get 'issuebook/viewissuedbooks'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :books
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'home/about'
  put '/issuebook/:id/', to: 'issuebook#issue', as: 'issuebook'
  delete '/issuebook/:id/', to: "issuebook#return"
  get '/issuebook/:id/', to: 'issuebook#viewissuedbooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, length: { minimum: 2, maximum: 50 }, presence: true
  validates :author, length: { minimum: 2, maximum: 50 }, presence: true
  validates :published_in,
            numericality: { less_than_or_equal_to: 2020, greater_than_or_equal_to: 1800, allow_nil: true }
  validates :volume, numericality: { greater_than_or_equal_to: 1, allow_nil: true }
  validate :validate_book

  def self.issuelogic(params, uid)
    book_id = params[:id]
    actiontype = params[:format]
    @book = Book.find(book_id)
    unless @book.availability.zero?
      @issued = Bookissue.find_by({ user_id: uid, book_id: @book.id })
      if @issued.blank?
        @issue_data = Bookissue.new({ user_id: uid, book_id: @book.id })
        @issue_data.save
        LibraryMailer.issue(@issue_data).deliver_later
        @book.decrement!(:availability) if actiontype == 'issue'
      end
    end
    @book
  end

  def self.returnlogic(params, uid)
    book_id = params[:id]
    actiontype = params[:format]
    @book = Book.find(book_id)
    @issue_data = Bookissue.find_by({ user_id: uid, book_id: @book.id })
    if @issue_data.present? && (actiontype == 'return')
      @book.increment!(:availability)
      @user = User.find(uid)
      ReturnMailerJob.perform(@book, @user)
      @issue_data.destroy
    end
    @book
  end
  has_many :bookissue, dependent: :destroy

  private

  def validate_book
    search_keyword = title.to_s.tr(' ', '+')
    url = "https://www.googleapis.com/books/v1/volumes?q=intitle:#{search_keyword}&key=AIzaSyDTwKE17DDbFVAOQl2OMyq-TlUFXDv56nY"
    uri = URI(url)
    api_response = Net::HTTP.get(uri)
    return if api_response.include? title.to_s

    errors.add(:base, 'It\'s not a valid book')
  end
end

app/models/bookissue.rb
class Bookissue < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, :set_book, only: %i[show edit update destroy]
  before_action :check_admin, except: %i[index show]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
      # @book.title
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_admin
    redirect_to books_path, notice: 'You are Not Authorized to perform this action' unless current_user&.admin
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :published_in, :volume, :availability)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to books_path
    end
  end
end

app/controllers/issuebook_controller.rb
class IssuebookController < ApplicationController
  def issue
    if user_signed_in?
      if Book.find(params[:id]).availability.zero?
        redirect_to books_url, notice: 'Availability is 0, cannot be issued'
      else
        Book.issuelogic(params, current_user.id)
        redirect_to books_url, notice: 'Book has been issued'
      end
      # else
      #   redirect_to new_user_session_path
    end
  end

  def return
    if user_signed_in?
      Book.returnlogic(params, current_user.id)
      # else
      #   redirect_to new_user_session_path
    end
    redirect_to books_url, notice: 'Book returned'
  end

  def viewissuedbooks
    @issuedbooks = Bookissue.where(user_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/issuebook_helper.rb
module IssuebookHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="field col-5 mx-auto mb-3">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li class="mt-1"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-5 mx-auto mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field col-5 mx-auto mb-3">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="field col-5 mx-auto mb-3">
    <%= form.label :published_in %>
    <%= form.number_field :published_in, class: 'form-control' %>
  </div>

  <div class="field col-5 mx-auto mb-3">
    <%= form.label :volume %>
    <%= form.number_field :volume, class: 'form-control' %>
  </div>

  <div class="actions col-5 mx-auto mb-3">
    <%= form.submit 'Submit', class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1 class="my-4 text-center">Editing Book</h1>

<%= render 'form', book: @book %>


<div class="col-5 mx-auto">
  <%= link_to 'Show', @book, class: 'me-1 btn btn-info' %>
  <%= link_to 'Back', books_path, class: 'ms-1 btn btn-secondary' %>
</div>

app/views/books/index.html.erb
<h1 class="text-center my-4">List of Books</h1>

<table class='table table-hover align-middle'>
  <thead class='table-info'>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Published in</th>
      <th>Volume</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td class="fs-5"><%= book.title %></td>
        <td class="fs-5"><%= book.author %></td>  
        <td class="fs-5"><%= book.published_in || '-' %></td>
        <td class="fs-5"><%= book.volume || '-' %></td>
        <td class="fs-5"><%= book.availability %></td>

        <td class="fs-5"><%= link_to 'View Book', book, class: 'btn btn-info btn-sm' %></td>
        
        <% if user_signed_in? && !current_user.admin %>
          <% if Bookissue.where(user_id: current_user.id, book_id: book.id).blank? %>
            <td class="fs-5"><%= link_to 'Issue', issuebook_path(book, 'issue'), method: :put,  class: 'btn btn-warning btn-sm' %></td>
          <% else %>
            <td class="fs-5"><%= link_to 'Return', issuebook_path(book, 'return'), method: :delete,  class: 'btn btn-secondary btn-sm' %></td>
          <% end %>
        <% end %>
        <% if user_signed_in? && current_user.admin %>
          <td class="fs-5"><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-secondary btn-sm' %></td>
          <td class="fs-5"><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && current_user.admin %>
  <%= link_to 'Add New Book', new_book_path , class: 'btn btn-primary' %>  
<% end %>

app/views/books/new.html.erb
<h1 class="my-4 text-center">New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="card text-center shadow-lg bg-body rounded mt-5">
  <div class="card-header">
  <h1 class="card-title my-4 text-center"><%= @book.title %></h1>  
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush">
      <li class="list-group-item my-2 align-middle fs-5"><strong>Author:</strong> <%= @book.author %></li>
      <li class="list-group-item my-2 align-middle fs-5"><strong>Published in:</strong> <%= @book.published_in || 'NA' %></li>
      <li class="list-group-item my-2 align-middle fs-5"><strong>Volume:</strong> <%= @book.volume || 'NA' %></li>
      <li class="list-group-item my-2 align-middle fs-5"></li>
    </ul>
    <h4 class="card-title"><strong>Book Summary</strong></h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
    
  <div class="card-footer text-muted">
    <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-primary me-1 my-2' %> 
    <%= link_to 'Back', books_path, class: 'btn btn-secondary ms-1 my-2' %>
  </div>
</div>

app/views/home/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
  <div class="container text-center">
    <span class="text-white">&#169; books@Lib.com</span>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Library.com', root_path, class: 'navbar-brand mx-5' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Books', books_path, class: 'nav-link active' %>
        </li>

        <li class="nav-item">
          <%= link_to 'About', home_about_path, class: 'nav-link active' %>
        </li>
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Issued Books', issuebook_path(current_user.id), class: 'nav-link active' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link active' %>
          </li>
        
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link active' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link active' %>
          </li>
        
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link active' %>
          </li>
        <% end %>  
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class='about-text'>
    <h1 class='text-center'>Our History</h1>

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis odit illo voluptatem doloremque cumque repudiandae facere possimus et totam sunt, sint enim nesciunt omnis eum, ullam magni, sequi modi. Ullam suscipit molestias expedita, vero fuga culpa rerum sint id nostrum, eligendi eius nobis eos. A aspernatur illum, voluptas dolorum molestiae, ipsam repellat sunt voluptate magnam animi, amet doloribus consequatur culpa? Pariatur veniam tempore, error quod eveniet ab placeat aliquam neque odit expedita iusto recusandae temporibus reiciendis?
    </p>

    <p>Quidem dolorum ipsa nemo ex saepe tempore rem ducimus rerum molestias omnis quaerat quia tempora voluptate cum, ea possimus, asperiores libero quam reiciendis consequatur! Libero consequuntur rem quis voluptatum delectus sint excepturi eniet quis! Perferendis unde necessitatibus non maxime illum eos doloremque quasi repellat exercitationem quam rem, inventore placeat fugiat libero, vitae perspiciatis a nisi iure officiis quod.
    </p>

    <p>Sit laudantium, neque dolore omnis cum consequatur optio blanditiis voluptatem? Odit aperiam sit alias similique saepe, delectus sed exercitationem labore, facilis boriosam nesciunt?
    </p>
    <p>Cumque sed consectetur minima natus quia corporis quisquam odio veniam, maxime accusamus hic aspernatur rerum ipsum reprehenderit laborum esse tempore, fugit asperiores provident soluta sapiente placeat nulla aliquam. Pariatur provident, ad ipsa facilis minima aliquid consectetur corporis quaerat perferendis similique itaque. </p>
    <p>Possimus nobis omnis doloremque non debitis, saepe incidunt aperiam quis iusto eos accusantium ullam itaque molestias odit porro quasi, perferendis impedit nam laudantium consequuntur? Quod nisi iusto magni repellat aperiam porro recusandae aliquid minima, numquam vero veniam delectus provident quam dolorum dolores totam! Quasi consectetur sapiente ex tenetur laboriosam cum deleniti corrupti dicta ea dignissimos. Facilis tenetur veritatis, corrupti dolore quis consequatur incidunt enim nemo vero, adipisci illum fugiat aliquid officiis. Culpa excepturi, id commodi blanditiis nesciunt in eveniet dolorum! Sit, omnis nihil!</p>
</div>

app/views/home/index.html.erb
<div class="col-10 text-center home-content border border-2 border-dark p-2">
    <h1>Welcome to Takshashila Library</h1>
    <p class="my-5"><em>“A reader lives a thousand lives before he dies . . . The man who never reads lives only one.”</em>   <strong>– George R.R. Martin</strong></p>
    <p class="my-5"><em>“There is more treasure in books than in all the pirate’s loot on Treasure Island.”</em>   <strong>– Walt Disney</strong></p>
    <p class="my-5"><em>“If you don’t like to read, you haven’t found the right book.”</em>   <strong>– J.K. Rowling</strong></p>
    <p class="my-5"><em>“Reading is important. If you know how to read, then the whole world opens up to you.”</em>   <strong>– Barack Obama</strong></p>
    <div>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary' %>
        <%= link_to 'Log in', new_user_session_path, class: 'btn btn-info' %>
    </div>
</div>

app/views/issuebook/viewissuedbooks.html.erb
<h1 class="text-center my-4">Issued Books</h1>

<table class='table table-hover align-middle'>
  <thead class='table-info'>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Published in</th>
      <th>Volume</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issuedbooks.each do |ib| %>
        <% book = Book.find(ib.book_id) %>
      <tr>
        <td class="fs-5"><%= book.title %></td>
        <td class="fs-5"><%= book.author %></td>
        <td class="fs-5"><%= book.published_in %></td>
        <td class="fs-5"><%= book.volume %></td>
        <td class="fs-5"><%= book.availability %></td>

        <td class="fs-5"><%= link_to 'View Book', book, class: 'btn btn-info btn-sm' %></td>
        
        <% if user_signed_in? && !current_user.admin%>
          <% if Bookissue.where(user_id: current_user.id, book_id: book.id).blank? %>
            <td class="fs-5"><%= link_to 'Issue', issuebook_path(book, 'issue'), method: :put,  class: 'btn btn-warning btn-sm' %></td>
          <% else %>
            <td class="fs-5"><%= link_to 'Return', issuebook_path(book, 'return'), method: :delete,  class: 'btn btn-secondary btn-sm' %></td>
          <% end %>
        <% end %>
        <% if user_signed_in? && current_user.admin %>
          <td class="fs-5"><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-secondary btn-sm' %></td>
          <td class="fs-5"><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'home/header' %>
    <!--<p class="notice alert alert-primary alert-dismissable fade show"><%= notice %></p>-->
    <!--<p class="alert"><%= alert %></p>-->
    <div class='container mx-auto min-vh-100'>
      <% if notice %>
        <div class="notice alert alert-warning alert-dismissible fade show mt-2" role="alert">
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  <div id="footer">
      <%= render 'home/footer' %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>